### ISSUE TITLE
Compilation using Rust nightly fails.

### ISSUE THREAD

**Issue by MalteT** [klemens/2i-emulator#8]
Compilation using Rust nightly fails for me, due to the custom rustyline dependency. It's propably an issue with your rustyline fork.

Error:
```
error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
    --> /home/malte/.cargo/git/checkouts/rustyline-c88f83e46ecbf954/291927c/src/lib.rs:1165:49
     |
1165 |                 self.editor.add_history_entry(l.as_ref()); // TODO Validate
     |                                                 ^^^^^^

```

Rust version: `rustc 1.39.0-nightly (521d78407 2019-08-25)`

**Comment by MalteT** [comment]
Stable does not work for me either: `rustc 1.37.0 (eae3437df 2019-08-13)`

**Comment by klemens** [comment]
Works again, tested with 1.38.0 and nightly 2019-10-23. Thanks for letting me know!
