### ISSUE TITLE
Not building on 1.44.0

### ISSUE THREAD

**Issue by ghost** [klemens/2i-emulator#9]
The project is not building on rust 1.44.0 since the package name starts with a number ("2").
To get it to build i had to change the name in the Cargo.toml file to something like "e2i-emulator".

**Comment by klemens** [comment]
Thanks for reporting! Interestingly this new restriction wasn't mentioned in the release notes and is currently also not mentioned in the reference. It was introduced in https://github.com/rust-lang/cargo/pull/7959.

I guess `emulator-2i` for the package it is!
